### PR TITLE
[WIP] adding routes to show for now

### PR DESCRIPTION
**Pull request by niklashof**
adding existing routes with the design by Nika to immediately have a couple of routes available

---

Requires #28

### CODE REVIEW

**Comment by lucasmichot** [comment]
Can this be closed ?

**Comment by niklashof** [comment]
not yet, once I am done with #28 I will close it

**Comment by lucasmichot** [comment]
OK, I've updated initial description.

**Comment by lucasmichot** [comment]
Merge into develop

**Pull request merged**
